---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-simple-app
  labels:
    app: liatrio-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liatrio-simple-app
  template:
    metadata:
      labels:
        app: liatrio-simple-app
    spec:
      containers:
      - name: liatrio-simple-app
        image: public.ecr.aws/r0a5m2j1/liatrio-simple-app:latest
        ports:
        - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: internal-liatrio-simple-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: liatrio-simple-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: external-liatrio-simple-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: liatrio-simple-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5080
